#!/bin/bash

cd $(dirname $0) || exit

# Set the backup directory (ideally from an environment variable)
BACKUP_DIR=${BACKUP_DIR:-"/home/wlmoj/backups"} # Default to /home/wlmoj/backups if BACKUP_DIR is not set

. ./utils/notify

if [ -z "$1" ]; then
  FILE_PREFIX="dump"
else
  # Sanitize the user-provided filename prefix (remove invalid characters and path elements)
  FILE_PREFIX=$(echo "$1" | sed -e 's/[^A-Za-z0-9_-]/_/g' -e 's#/#_#g')
fi

TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
BACKUP_FILE="$BACKUP_DIR/${FILE_PREFIX}_${TIMESTAMP}.sql.gz"

cd "$(dirname "$(dirname "$0")")" || exit

set -a
.  environment/mysql.env
set +a

# Check the exit status of mariadb-dump
if ! docker compose exec db mariadb-dump --all-databases --single-transaction --ssl="FALSE" --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" | gzip > "$BACKUP_FILE"; then
    echo "ERROR: mariadb-dump failed. Check logs for details."
    notify "Backup Failed" "true"
    exit 1
fi

echo "Backup created successfully: $BACKUP_FILE"
