#!/bin/bash

pwd

echo "$CI" # Debugging



if [ -z "$CI" ]; then  # Not running in CI
         bash /scripts/make_style.sh && \
         cd /site && \
         python3 manage.py collectstatic --noinput && \
         python3 manage.py compilemessages && \
         python3 manage.py compilejsi18n && \
         cp -r resources/ /assets/ && \
         rm resources/style.css resources/martor-description.css resources/select2-dmoj.css resources/ace-dmoj.css && \
         rm resources/dark/style.css resources/dark/martor-description.css resources/dark/select2-dmoj.css resources/dark/ace-dmoj.css && \
         rm -r sass_processed && \
         cp 502.html /assets/ && \
         cp logo.png /assets/ && \
         cp robots.txt /assets/
else # in CI
  docker compose -f ./docker-build.yml exec "$COMPOSE_EXEC_FLAGS" site /bin/bash -c "\
      bash make_style.sh && \
      mkdir ./assets && \
      python3 manage.py collectstatic --noinput && \
      python3 manage.py compilemessages && \
      python3 manage.py compilejsi18n && \
      cp -r resources/ ./assets/ && \
      rm resources/style.css resources/martor-description.css resources/select2-dmoj.css resources/ace-dmoj.css && \
      rm resources/dark/style.css resources/dark/martor-description.css resources/dark/select2-dmoj.css resources/dark/ace-dmoj.css && \
      rm -r sass_processed && \
      cp 502.html ./assets/ && \
      cp logo.png ./assets/ && \
      cp robots.txt ./assets/"
fi
