#!/bin/bash
cd $(dirname $(dirname $0)) || exit

if [ -z "$CI" ]; then  # Not running in CI
      mkdir -p /var/share/problems /var/share/media
      cp ../config.js /var/share/configs/websocket/
      cp ../local_settings.py /var/share/configs/wlmoj/
      cp ../uwsgi.ini /var/share/configs/wlmoj/
      cp ./mathoid/config.yaml /var/share/configs/mathoid/
      cp -R ../nginx/conf.d/ /var/share/configs/nginx/
else # in CI
  sudo apt-get install tree
  pwd
  tree -a -f ${GITHUB_WORKSPACE}
  mkdir -p websocket
  cp ../local_settings.py ${GITHUB_WORKSPACE}/dmoj/repo/local_settings.py
  cp ../config.js ${GITHUB_WORKSPACE}/dmoj/repo/websocket/config.js
#  cp ../uwsgi.ini ${GITHUB_WORKSPACE}/uwsgi.ini
fi
