#!/bin/bash
cd $(dirname $(dirname $0)) || exit

if [ -z "$CI" ]; then  # Not running in CI
      mkdir -p /var/share/problems /var/share/media
      cp ../config.js /var/share/configs/websocket/
      cp ../local_settings.py /var/share/configs/wlmoj/
      cp ../uwsgi.ini /var/share/configs/wlmoj/
      cp ./mathoid/config.yaml /var/share/configs/mathoid/
      cp -R ../nginx/conf.d/ /var/share/configs/nginx/
else
  mkdir -p repo repo/websocket repo/dmoj
  cp ../config.js repo/websocket/
  cp ../local_settings.py repo/dmoj/
  cp ../uwsgi.ini repo/
fi
