#!/bin/bash
cd $(dirname $(dirname $0)) || exit
. ./utils/notify
set -e
if [ -z "$1" ]; then
    echo "Usage: restore <filename.sql>"
    echo "Example: restore 2024-06-28_15-25-00.sql"
    exit 1  # Exit with an error code
fi

BACKUP_FILE="$1"
DOCKER_ID=$(docker ps -qf "name=db")
# Verify if the backup file exists
if [ ! -f "$BACKUP_FILE" ]; then
    echo "Error: Backup file '$BACKUP_FILE' not found."
    exit 1  # Exit with an error code
fi

notify "Restore Started"

set -a
.  environment/mysql.env
set +a

# todo: add pv? (pipe viewer) to show progress bar
# gunzip -c "${BACKUP_FILE}" | docker exec -i DOCKER_ID mariadb --user="$MYSQL_USER
docker exec "$DOCKER_ID" mariadb --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" < "${BACKUP_FILE}"

echo "Restore completed successfully."
notify "Restore Completed" "true"
