version: '3.8'
services:
  texoid:
    image: ghcr.io/mcpt/wlmoj-texoid
    init: true
    networks:
        - site

  pdfoid:
    image: ghcr.io/mcpt/wlmoj-pdfoid
    init: true
    networks:
        - site
    cap_add:
      - SYS_ADMIN
    deploy:
        resources:
            limits:
              memory: 512M
        placement:
          constraints: [ node.role == worker ]

  mathoid:
    image: ghcr.io/mcpt/wlmoj-mathoid
    init: true
    networks:
        - site
    deploy:
        resources:
            limits:
              memory: 512M
        placement:
          constraints: [ node.role == worker ]

  site:
    image: ghcr.io/mcpt/wlmoj-site
    init: true
    user: "root:9889"
    volumes:
      - /var/share/assets:/assets/
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/share/cache/cache:/cache/
      - /var/share/media:/media/
      - /var/share/problems:/problems/
      - /var/share/logs:/logs/
      - /site/:/site/
      - /var/share/configs/wlmoj/local_settings.py:/site/dmoj/local_settings.py:ro
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks:
      - site
      - db
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
         parallelism: 1
         delay: 1m
         failure_action: rollback

  celery:
    image: ghcr.io/mcpt/wlmoj-celery
    init: true
    user: "root:9889"
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/share/logs:/logs/
      - /site/:/site/
      - /var/share/configs/wlmoj/local_settings.py:/site/dmoj/local_settings.py:ro
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks:
        - site
        - db
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
         parallelism: 1
         delay: 1m
         failure_action: rollback

  bridged:
    image: ghcr.io/mcpt/wlmoj-bridged
    init: true
    user: "root:9889"
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/problems/:/problems/
      - /var/share/logs:/logs/
      - /site/:/site/
      - /var/share/configs/wlmoj/local_settings.py:/site/dmoj/local_settings.py:ro
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks:
        - site
        - db
    ports:
      - "9999:9999"
      - "9998:9998"
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]

  wsevent:
    image: ghcr.io/mcpt/wlmoj-wsevent
    init: true
    user: "root:9889"
    volumes:
      - /site/:/app/site/
      - /var/share/configs/wsevent/config.js:/app/site/websocket/config.js:ro
    working_dir: /app/site
    env_file: [environment/mysql.env, environment/site.env]
    networks:
        - site
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]

  db:
    image: mariadb
    volumes:
      - /home/judge/database/:/var/lib/mysql:Z
      - ./scripts/mariadb:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /home/judge/backups:/backups
    env_file: [ environment/mysql.env, environment/mysql-admin.env ]
    ports:
      - "3306:3306"
    environment:
      TZ: "America/Toronto"
    networks:
        - db
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == general ]

  redis:
    image: redis:alpine
    networks:
      - site
    deploy:
      replicas: 1

  nginx:
    image: ghcr.io/mcpt/wlmoj-nginx
    user: "root:9889"
    ports:
      - "80:80"
    volumes:
      - /var/share/assets/:/assets/
      - /var/share/cache/pdfcache/:/pdfcache/
      - /var/share/cache/datacache/:/datacache/
      - /var/cache/cache:/cache/
      - /var/share/media/:/media/
    networks:
      - site
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [ node.hostname == general ]

#  judge:
#    container_name: dmoj_judge
#    image: ghcr.io/mcpt/wlmoj-judge
#    deploy:
#      replicas: 1 # 1 by default but can be scaled up


networks:
  site:
    driver: overlay
  db:
    driver: overlay
