version: '3.8'
services:
  texoid:
    build:
      context: .
      dockerfile: ./texoid/Dockerfile
    image: ghcr.io/mcpt/wlmoj-texoid
    init: true
    restart: unless-stopped
    networks: [site]

  pdfoid:
    build:
      context: .
      dockerfile: ./pdfoid/Dockerfile
    image: ghcr.io/mcpt/wlmoj-pdfoid
    init: true
    restart: unless-stopped
    networks: [site]
    cap_add:
      - SYS_ADMIN
  mathoid:
    build:
      context: .
      dockerfile: ./mathoid/Dockerfile
    image: ghcr.io/mcpt/wlmoj-mathoid
    init: true
    restart: unless-stopped
    volumes:
      - ./mathoid/config.yaml:/node_modules/mathoid/config.yaml
    networks: [site]

  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: ghcr.io/mcpt/wlmoj-base
    network_mode: none

  site:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    image: ghcr.io/mcpt/wlmoj-site
    init: true
    restart: unless-stopped
    volumes:
      - /var/share/assets:/share/assets/
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/cache/cache:/cache/
      - /var/share/media/:/media/
      - /var/share/problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    depends_on: [base, db, redis]
    deploy:
     update_config:
         parallelism: 1
         delay: 1m
         failure_action: rollback

  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    image: ghcr.io/mcpt/wlmoj-celery
    init: true
    restart: unless-stopped
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, db]
    depends_on: [base, db, redis]

  bridged:
    build:
      context: .
      dockerfile: ./bridged/Dockerfile
    image: ghcr.io/mcpt/wlmoj-bridged
    init: true
    restart: unless-stopped
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    ports:
      - "9999:9999"
    depends_on: [base, db, redis]
  wsevent:
    build:
      context: .
      dockerfile: ./wsevent/Dockerfile
    image: ghcr.io/mcpt/wlmoj-wsevent
    init: true
    restart: unless-stopped
    volumes:
      - ./repo/:/app/site/
    working_dir: /app/site
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx]

  db:
    image: mariadb
    restart: always
    volumes:
      - database:/var/lib/mysql/
    env_file: [ environment/mysql.env, environment/mysql-admin.env ]
    networks: [ db ]
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  redis:
    image: redis:alpine
    restart: always
    networks: [ site ]

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/share/assets:/share/assets/
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/cache/cache:/cache/
      - /var/share/media/:/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: [nginx]
    depends_on: [site, wsevent]

  judge:
    container_name: dmoj_judge
    image: ghcr.io/mcpt/wlmoj-judge
    restart: always
    deploy:
      replicas: 1 # 1 by default but can be scaled up


networks:
  site:
  db:
  nginx:




volumes:
  database:
