services:
  texoid:
    image: ghcr.io/mcpt/wlmoj-texoid
    init: true
    networks:
      - site
    deploy:
      resources:
        limits:
          memory: 128M
      endpoint_mode: dnsrr
      placement:
        constraints: [ node.role == worker ]

  pdfoid:
    image: ghcr.io/mcpt/wlmoj-pdfoid
    init: true
    networks:
      - site
    cap_add:
      - SYS_ADMIN
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 256M
      placement:
        constraints: [ node.role == worker ]

  mathoid:
    image: ghcr.io/mcpt/wlmoj-mathoid
    init: true
    networks:
      - site
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 256M
      placement:
        constraints: [ node.role == worker ]

  site:
    image: ghcr.io/mcpt/wlmoj-site
    init: true
    user: "1000:9889"
    volumes:
      - /var/share/assets:/assets/
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/share/cache/mathoid:/mathoid/
      - /var/share/cache/texoid:/texoid/
      - /var/share/media:/media/
      - /var/share/problems:/problems/
      - /var/share/logs:/logs/
      - /site/:/site/
      - /var/share/configs/wlmoj/local_settings.py:/site/dmoj/local_settings.py
    working_dir: /site/
    env_file: [ environment/mysql.env, environment/site.env ]
    networks:
      - site
      - judge
      - db
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [ node.role == worker ]
      update_config:
        parallelism: 1
        delay: 1m
        failure_action: rollback

  celery:
    image: ghcr.io/mcpt/wlmoj-celery
    init: true
    user: "1000:9889"
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/share/logs:/logs/
      - /site/:/site/
      - /var/share/configs/wlmoj/local_settings.py:/site/dmoj/local_settings.py
    working_dir: /site/
    env_file: [ environment/mysql.env, environment/site.env ]
    networks:
      - site
      - db
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [ node.role == worker ]
      update_config:
        parallelism: 1
        delay: 1m
        failure_action: rollback

  bridged:
    image: ghcr.io/mcpt/wlmoj-bridged
    init: true
    user: "1000:9889"
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/problems/:/problems/
      - /var/share/logs:/logs/
      - /site/:/site/
      - /var/share/configs/wlmoj/local_settings.py:/site/dmoj/local_settings.py
    working_dir: /site/
    env_file: [ environment/mysql.env, environment/site.env ]
    networks:
      - site
      - judge
      - db
#    ports:
#      - "9999:9999"
#      - "9998:9998"
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  wsevent:
    image: ghcr.io/mcpt/wlmoj-wsevent
    init: true
    user: "root:9889"
    volumes:
      - /site/:/app/site/
    working_dir: /app/site
    env_file: [ environment/mysql.env, environment/site.env ]
    networks:
      - site
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  db:
    image: mariadb
    volumes:
      - /home/judge/database/:/var/lib/mysql:Z
      - ./scripts/mariadb:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /home/judge/backups:/backups
    env_file: [ environment/mysql.env, environment/mysql-admin.env ]
#    ports:
#      - "3306:3306"
    environment:
      TZ: "America/Toronto"
    networks:
      - db
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [ node.hostname == general ]

  sentinel:
    image: ghcr.io/mcpt/sentinel:main
    volumes:
      - /var/share/:/var/share/:ro
      - /var/share/configs/backups/config.toml:/config.toml:ro
    command: "--config-file /config.toml"
    networks:
      - db
    deploy:
      replicas: 1

  redis:
    image: redis:alpine
    networks:
      - db
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  nginx:
    image: ghcr.io/mcpt/wlmoj-nginx
    user: "root:9889"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/share/assets/:/assets/
      - /var/share/cache/pdfcache/:/pdfcache/
      - /var/share/cache/datacache/:/datacache/
      - /var/share/cache/texoid/:/texoid/
      - /var/share/cache/mathoid/:/mathoid
      - /var/share/media/:/media/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - site
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]

  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/letsencrypt/letsencrypt.log:/var/log/letsencrypt/letsencrypt.log
      - /var/share/configs/certbot/cloudflare.ini:/root/.secrets/certbot/cloudflare.ini:ro
    command: certonly -v --non-interactive --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/certbot/cloudflare.ini --dns-cloudflare-propagation-seconds=50 --email dns@mcpt.ca --agree-tos --no-eff-email -d mcpt.ca -d mcpt.ca
    deploy:
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        delay: 24h

networks:
  site:
    driver: overlay
  db:
    driver: overlay
  judge:
    driver: overlay
    attachable: true
