version: '3.8'
services:
  texoid:
    build:
      context: .
      dockerfile: ./texoid/Dockerfile
    image: ghcr.io/mcpt/wlmoj-texoid
    init: true
    restart: unless-stopped
    networks: [site]

  pdfoid:
    build:
      context: .
      dockerfile: ./pdfoid/Dockerfile
    image: ghcr.io/mcpt/wlmoj-pdfoid
    init: true
    restart: unless-stopped
    networks: [site]
    cap_add:
      - SYS_ADMIN
    deploy:
        resources:
            limits:
              memory: 512M
        placement:
          constraints: [ node.role == worker ]

  mathoid:
    build:
      context: .
      dockerfile: ./mathoid/Dockerfile
    image: ghcr.io/mcpt/wlmoj-mathoid
    init: true
    restart: unless-stopped
    networks: [site]

    deploy:
        resources:
            limits:
              memory: 512M
        placement:
          constraints: [ node.role == worker ]


  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: ghcr.io/mcpt/wlmoj-base
    network_mode: none
    deploy:
      replicas: 0 # don't run this as a service, it is just used for the build process


  site:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    image: ghcr.io/mcpt/wlmoj-site
    init: true
    restart: unless-stopped
    volumes:
      - /var/share/assets:/assets/
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/share/cache/cache:/cache/
      - /var/share/media:/media/
      - /var/share/problems:/problems/
      - /var/share/logs:/logs/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    depends_on: [base, db, redis]
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
         parallelism: 1
         delay: 1m
         failure_action: rollback

  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    image: ghcr.io/mcpt/wlmoj-celery
    init: true
    restart: unless-stopped
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/share/logs:/logs/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, db]
    depends_on: [base, db, redis]
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
         parallelism: 1
         delay: 1m
         failure_action: rollback

  bridged:
    build:
      context: .
      dockerfile: ./bridged/Dockerfile
    image: ghcr.io/mcpt/wlmoj-bridged
    init: true
    restart: unless-stopped
    volumes:
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/problems/:/problems/
      - /var/share/logs:/logs/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    ports:
      - "9999:9999"
    depends_on: [base, db, redis]
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]

  wsevent:
    build:
      context: .
      dockerfile: ./wsevent/Dockerfile
    image: ghcr.io/mcpt/wlmoj-wsevent
    init: true
    restart: unless-stopped
    working_dir: /app/site
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx]
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]

  db:
    image: mariadb
    restart: always
    volumes:
      - /home/wlmoj/database/:/var/lib/mysql:Z
      - ./scripts/mariadb:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /home/wlmoj/backups:/backups
    env_file: [ environment/mysql.env, environment/mysql-admin.env ]
    environment:
      TZ: "America/Toronto"
    networks: [ db ]
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  redis:
    image: redis:alpine
    restart: always
    networks: [ site ]
    deploy:
      replicas: 1

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/share/assets:/assets/
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/cache/cache:/cache/
      - /var/share/media/:/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: [nginx]
    depends_on: [site, wsevent]
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == general] # Only deploy on the general node as it's the entrypoint

#  judge:
#    container_name: dmoj_judge
#    image: ghcr.io/mcpt/wlmoj-judge
#    restart: always
#    deploy:
#      replicas: 1 # 1 by default but can be scaled up


networks:
  site:
  db:
  nginx:
