services:
  texoid:
    build:
      context: ./texoid/
    image: ghcr.io/mcpt/wlmoj-texoid
    init: true
    restart: unless-stopped
    networks: [ site ]

  pdfoid:
    build:
      context: ./pdfoid/
    image: ghcr.io/mcpt/wlmoj-pdfoid
    init: true
    restart: unless-stopped
    networks: [ site ]
    cap_add:
      - SYS_ADMIN

  mathoid:
    build:
      context: ./mathoid/
    image: ghcr.io/mcpt/wlmoj-mathoid
    init: true
    restart: unless-stopped
    networks: [ site ]


  base:
    build:
      context: ./base/
    image: ghcr.io/mcpt/wlmoj-base
    network_mode: none

  site:
    build:
      context: . # so we can grab scripts on build
      dockerfile: ./site/Dockerfile
    image: ghcr.io/mcpt/wlmoj-site
    init: true
    restart: unless-stopped
    volumes:
      - /var/share/assets:/assets/
      - /var/share/cache/pdfcache:/pdfcache/
      - /var/share/cache/datacache:/datacache/
      - /var/share/cache/mathoid:/mathoid/
      - /var/share/cache/mathoid:/texoid/
      - /var/share/media:/media/
      - /var/share/problems:/problems/
      - /var/share/logs:/logs/
      - ${GITHUB_WORKSPACE}/dmoj/repo/:/site/
    working_dir: /site/
    env_file: [ environment/mysql.env, environment/site.env ]
    networks: [ site, nginx, db ]
    depends_on: [ base, db, redis ]

  celery:
    build:
      context: ./celery/
    image: ghcr.io/mcpt/wlmoj-celery
    init: true
    restart: unless-stopped
    volumes:
      - /pdfcache:/pdfcache/
      - /datacache:/datacache/
      - /logs/:/logs/
      - ${GITHUB_WORKSPACE}/dmoj/repo:/site/
    working_dir: /site/
    env_file: [ environment/mysql.env, environment/site.env ]
    networks: [ site, db ]
    depends_on: [ base, db, redis ]

  bridged:
    build:
      context: ./bridged/
    image: ghcr.io/mcpt/wlmoj-bridged
    init: true
    restart: unless-stopped
    volumes:
      - /pdfcache:/pdfcache/
      - /problems/:/problems/
      - /logs:/logs/
      - ${GITHUB_WORKSPACE}/dmoj/repo/:/site/
    working_dir: /site/
    env_file: [ environment/mysql.env, environment/site.env ]
    networks: [ site, db ]
    ports:
      - "9999:9999"
    depends_on: [ base, db, redis ]


  wsevent:
    build:
      context: ./wsevent/
    image: ghcr.io/mcpt/wlmoj-wsevent
    init: true
    restart: unless-stopped
    volumes:
      - ${GITHUB_WORKSPACE}/dmoj/repo/:/app/site/
    working_dir: /app/site
    env_file: [ environment/mysql.env, environment/site.env ]
    networks: [ site, nginx ]

  db:
    image: mariadb
    restart: always
    volumes:
      - ./scripts/mariadb:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
    env_file: [ environment/mysql.env, environment/mysql-admin.env ]
    environment:
      TZ: "America/Toronto"
    networks: [ db ]

  redis:
    image: redis:alpine
    restart: always
    networks: [ site ]

  nginx:
    build:
      context: ./nginx/
    image: ghcr.io/mcpt/wlmoj-nginx
    init: true
    restart: always
    ports:
      - "80:80"
    volumes:
      - /assets:/assets/
      - /pdfcache:/pdfcache/
      - /datacache:/datacache/
      - /cache:/cache/
      - /media/:/media/
    networks: [ nginx ]
    depends_on: [ site, wsevent ]

networks:
  site:
  db:
  nginx:
