- name: Create docker group
  group:
    name: docker
    state: present

- name: Add judge user
  user:
    name: judge
    groups:
      - sudo
      - docker
    append: yes
    shell: /bin/bash
    password: "$6$lM0.82iYD1grZyfV$GEjJtEY8csAy2m4SRhxH1QRXuKvvT.iSvPnRyPL16HBsvHaB8ZFLhIUrI8oeMEhd0IGXiPbTAbSilM0uvx2zw/" # Please Contact Judge Lead For Password


- name: Add Json's SSH Keys
  ansible.posix.authorized_key:
    user: judge
    state: present
    key: "{{ lookup('url', 'https://github.com/JasonLovesDoggo.keys', split_lines=False) }}"

