- name: Remove old docker artifacts
  community.docker.docker_prune:
    containers: true
    images: true
    containers_filters:
      until: 6h
    # only consider containers created more than 6 hours ago
    networks: true
    volumes: true
    builder_cache: true


