- name: Allow TCP port 22 (SSH)
  ufw:
    rule: allow
    port: 22
    proto: tcp
- name: Allow TCP port 2376 (Docker Swarm manager communication)
  ufw:
    rule: allow
    port: 2376
    proto: tcp
- name: Allow TCP port 2377 (Docker Swarm manager communication)
  ufw:
    rule: allow
    port: 2377
    proto: tcp

- name: Allow TCP/UDP port 7946 (Overlay network discovery)
  ufw:
    rule: allow
    port: 7946

- name: Allow UDP port 4789 (Overlay network traffic)
  ufw:
    rule: allow
    port: 4789
    proto: udp
    to: '{{ overlay_network_range }}'  # Replace with your actual overlay network range
    from: '{{ overlay_network_range }}'

- name: Allow IP protocol 50 (IPSec ESP) for encrypted overlay networks (optional)
  ufw:
    rule: allow
    proto: esp
    to: '{{ overlay_network_range }}'
    from: '{{ overlay_network_range }}'
- name: Allow internal network communication (optional)
  ufw:
    rule: allow
    to: '{{ overlay_network_range }}'
    from: '{{ overlay_network_range }}'
- name: UFW - enable and by default drop
  ufw:
    state: enabled
    policy: deny
