---
- name: Create the homeshare group
  ansible.builtin.group:
    name: homeshare
    state: present
    system: true
    gid: 9889
  failed_when: false # Ignore failure if the group already exists

- name: Add root to the homeshare group
  ansible.builtin.user:
    name: root
    groups: homeshare
    append: true
