- name: create the homeshare group
  group:
    name: homeshare
    state: present
    system: yes
    gid: 9889
  failed_when: false # Ignore failure if the group already exists

- name: add root to the homeshare group
  user:
    name: root
    groups: homeshare
    append: yes
