- name: Create docker group
  group:
    name: docker
    state: present

- name: Add judge user
  user:
    name: judge
    id: 1000
    groups:
      - sudo
      - docker
    append: yes
    shell: /bin/bash
    password: "$6$lM0.82iYD1grZyfV$GEjJtEY8csAy2m4SRhxH1QRXuKvvT.iSvPnRyPL16HBsvHaB8ZFLhIUrI8oeMEhd0IGXiPbTAbSilM0uvx2zw/" # Please Contact Judge Lead For Password


- name: Add Json's SSH Keys
  ansible.posix.authorized_key:
    user: judge
    state: present
    key: "{{ lookup('url', 'https://github.com/JasonLovesDoggo.keys', split_lines=False) }}"


- name: Add Phil's SSH Keys
  ansible.posix.authorized_key:
    user: judge
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDb6wCbLHx+HZGBmcKu4mmPDxYoiW02aJPmdBgs4e3ZopPw0HZiqABsFe67qQAwGmnCUGa+RpwmttzW+pMbzdy2JZRjZAe/oN/Jzn7t+bJMWeam8OEjuCZmjnjyjBCtVYqfagN53h5CrTBsKQRfNYlqVmG6fhfAit4YLmaM/8AgwWfxp+MHKnVcOEZ2jfyNNKma7N89fVLnHNYyzbIin8TH74yiszMFPWBBxAL3SDdI1ks0ini2A9BDNTS6y35gId2EFDrb4KT+1hDa1Dl8KCLyIuv8qTEAKgDn+Zb+/5nz4dPsgh/lJXBG/WbaF6qvo8xGiZlJJV62uEDGZtC7HikMW4+5eXO4M0u5NcFfUv8MkWJMMLleNwjPFznKBjjIY5FbtXQYZCrsh0uk9fXRWufGRs0LtWR1JqyPTknSv07HYisFSCv60ETDsrnAfMzRxfDO46TAVTOGyShsAXEPqSZX1aaVqWkguLD0IjKZXKb583BqzBRrpJQcJ0jLU9GKYjM= philr@LAPTOP-LA865IKO"