- hosts: "{{ target }}"

  vars:
    # permissions on windows with wsl is not fun
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

    docker_edition: 'ce'
    docker_package_state: present
#    pip_install_packages:
#      - name: docker==7.1.0

#  roles:
##    - geerlingguy.docker

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Wait for APT Lock
      shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Install Docker
      run_once: true
      include_role:
        name: geerlingguy.docker

    - name: 'APT Upgrade'
      apt:
        upgrade: true
        update_cache: true



    - name: 'Install nfs & pip'
      apt:
        pkg:
          - nfs-common
          - python3-pip

    - name: 'Mount nfs share'
      run_once: true
      ansible.posix.mount:
        path: /var/share
        src: 10.137.0.5:/var/share
        state: mounted
        fstype: nfs4
        opts: 'auto,nofail,noatime,nolock,intr,tcp,actimeo=1800'

    - name: 'Change timezone to Toronto time'
      shell: timedatectl set-timezone America/Toronto

    - name: "Install updated docker bindings"
      pip:
        name: docker>=7.1.0

    - name: 'Get WLMOJ Repo'
      environment:
        GIT_TERMINAL_PROMPT: 0
      ansible.builtin.git:
        repo: 'https://github.com/mcpt/wlmoj.git'
        clone: true
        recursive: true
        dest: '/site'


#    - name: 'run submodules'
#      shell: 'git submodule update --init --recursive'
#      args:
#        chdir: '/site'

    - name: 'Install UFW'
      run_once: true
      apt:
        name: ufw

    - name: "UFW: allow ssh"
      run_once: true
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: 'UFW: internal network'
      run_once: true
      ufw:
        rule: allow
        src: '10.137.0.0/16'
        dest: '10.137.0.0/16'
    - name: 'UFW: Allow overlay networking'
      run_once: true
      ufw:
        rule: allow
        port: 4789


    - name: 'UFW: enable and by default drop'
      ufw:
        state: enabled
        policy: deny

    - name: 'Disable password for root'
      shell: passwd -d root
      run_once: true


    - name: "Install common utils"
      apt:
        pkg:
          - vim
          - btop
          - ncdu
          - jq
          - curl
    - name: 'Get Swarm join token from manager'
      run_once: true
      shell: 'docker swarm join-token worker -q'
      register: join_token
      delegate_to: "{{ groups['managers'] | random }}"  # Run on the first manager node

    - name: 'Join the Swarm as a worker'
      run_once: true
      community.docker.docker_swarm:
        state: join
        join_token: "{{ join_token.stdout_lines[0] }}"
        advertise_addr: "{{ groups['managers'][0] }}"  # Use Docker factP
        remote_addrs: "{{ groups['managers'] }}"

    - name: 'Reboot server'
      reboot:

    - name: 'Install Unattended Upgrades'
      include_role:
        name: hifis.unattended_upgrades
