target: managers
vars:
  overlay_network_range: "10.137.0.0/16"
# https://stackoverflow.com/a/63411562/18516611
# Ensure that the swarm is created using the proper INTERFACE instead of ip
tasks:
  - name: 'Change timezone to Toronto time'
    shell: timedatectl set-timezone America/Toronto

  - name: 'Install nfs, pip & ufw'
    apt:
      pkg:
        - nfs-common
        - python3-pip
        - ufw
        - python3-jsondiff   # Used for ansible-dockerpw


  - name: Ensure .ssh directory exists
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.ssh"
      state: directory
      mode: '0700'

  - name: Ensure SSH config file exists
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.ssh/config"
      state: touch
      mode: '600'

  - name: Add specific SSH config for Host 10.137.0.0/16
    ansible.builtin.lineinfile:
      mode: '400'
      path: "{{ ansible_env.HOME }}/.ssh/config"
      line: "Host 10.137.0.0/16\n    StrictHostKeyChecking no"
      create: yes
      insertafter: EOF


  - name: "Run network tasks"
    ansible.builtin.include_tasks: "tasks/networking.yml"

  - name: Install Docker
    run_once: true
    include_role:
      name: jsoncameron.docker

  - name: Ensure /etc/docker directory exists
    file:
      path: /etc/docker
      state: directory
      mode: '0755'

  - name: Configure Docker daemon
    copy:
      content: |
        {
          "dns": ["8.8.8.8", "8.8.4.4"]
        }
      dest: /etc/docker/daemon.json
    register: daemon_config

  - name: Ensure certbot is installed
    apt:
      name: certbot
      state: present

  - name: Create directory for SSL certificates
    file:
      path: /etc/letsencrypt
      state: directory

  - name: Obtain SSL certificate
    command: >
      certbot certonly --standalone
      -d test.mcpt.ca
      --email admin@mcpt.ca
      --agree-tos
      --non-interactive
      --expand
    args:
      creates: /etc/letsencrypt/live/test.mcpt.ca/fullchain.pem

  - name: Set up automatic renewal
    cron:
      name: "Renew Let's Encrypt certificates"
      job: "/usr/bin/certbot renew --quiet --deploy-hook 'docker service update --force wlmoj_nginx'"
      minute: "0"
      hour: "0"
      day: "1"
      month: "*"


#  root@general /h/w/d/dmoj (master) [1]# sudo ufw allow proto tcp from 10.137.0.0/16 to 10.137.0.0/16 port 2377
#  Rule added
#  root@general /h/w/d/dmoj (master)# sudo ufw allow proto any from 10.137.0.0/16 to 10.137.0.0/16 port 7947
#  Rule added
#  root@general /h/w/d/dmoj (master)# sudo ufw allow proto udp from 10.137.0.0/16 to 10.137.0.0/16 port 4789

# sudo ufw allow from 10.137.0.0/16 to any port nfs





# docker network create --driver overlay --ingress --subnet=10.137.0.0/16 --gateway=10.137.0.5 --opt com.do
#cker.network.driver.mtu=1200 ingress ||||| where 0.5 is general's iIP
