- hosts: "workers"
  become: true
  become_user: root
  strategy: linear


  vars:
    # permissions on windows with wsl is not fun
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

    docker_edition: 'ce'
    docker_package_state: present


  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: 'Get WLMOJ Repo'
      environment:
        GIT_TERMINAL_PROMPT: 0
      ansible.builtin.git:
        repo: 'https://github.com/mcpt/wlmoj.git'
        clone: true
        recursive: true
        dest: '/site'

    - name: 'Disable password for root'
      shell: passwd -d root
      run_once: true

    - name: Ensure Locks Are Released
      shell:
        cmd: |
          while fuser /var/lib/apt/lists/lock /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock >/dev/null 2>&1; do
            sleep 2
          done
      register: locks_released
      until: locks_released.rc == 0
      retries: 10
      delay: 5

    - name: Install Docker
      run_once: true
      include_role:
        name: geerlingguy.docker

    - name: 'Install nfs, pip & ufw'
      apt:
        pkg:
          - nfs-common
          - python3-pip
          - ufw

    - name: 'Mount nfs share'
      run_once: true
      ansible.posix.mount:
        path: /var/share
        src: 10.137.0.5:/var/share
        state: mounted
        fstype: nfs4
        opts: 'auto,nofail,noatime,nolock,intr,tcp,actimeo=1800'

    - name: 'Change timezone to Toronto time'
      shell: timedatectl set-timezone America/Toronto

    - name: "Install updated docker bindings"
      pip:
        name: docker>=7.1.0


    - name: "UFW: allow ssh"
      run_once: true
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: 'UFW: internal network'
      run_once: true
      ufw:
        rule: allow
        src: '10.137.0.0/16'
        dest: '10.137.0.0/16'
    - name: 'UFW: Allow overlay networking'
      run_once: true
      ufw:
        rule: allow
        port: 4789


    - name: 'UFW: enable and by default drop'
      ufw:
        state: enabled
        policy: deny


    - name: "Install common utils"
      apt:
        pkg:
          - vim
          - btop
          - ncdu
          - jq
          - curl


    - name: Get Swarm join token from manager
      ansible.builtin.delegate_to:
        host: "{{ groups['managers'][0] }}"  # Delegate to manager
      tasks: # Nested tasks within delegate_to
        - name: Run the command
          ansible.builtin.shell: "docker swarm join-token worker -q"
          register: join_token  # Store the output

    - name: 'Join the Swarm as a worker'
      run_once: true
      community.docker.docker_swarm:
        state: join
        join_token: "{{ join_token.stdout }}"
        advertise_addr: "{{ groups['managers'][0] }}"  # Use Docker factP
        remote_addrs: "{{ groups['managers'] }}"

    - name: Ensure Locks Are Released
      shell:
        cmd: |
          while fuser /var/lib/apt/lists/lock /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock >/dev/null 2>&1; do
            sleep 2
          done
      register: locks_released
      until: locks_released.rc == 0
      retries: 10
      delay: 5

    - name: 'Install Unattended Upgrades'
      include_role:
        name: hifis.unattended_upgrades


    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: 'Reboot server'
      reboot:
        when:
          when: reboot_required_file.stat.exists == true



