target: managers

tasks:
  - name: 'Change timezone to Toronto time'
    shell: timedatectl set-timezone America/Toronto

  - name: 'Install nfs, pip & ufw'
    apt:
      pkg:
        - nfs-common
        - python3-pip
        - ufw
        - python3-jsondiff   # Used for ansible-dockerpw


  - name: Ensure .ssh directory exists
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.ssh"
      state: directory
      mode: '0700'

  - name: Ensure SSH config file exists
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.ssh/config"
      state: touch
      mode: '600'

  - name: Add specific SSH config for Host 10.137.0.0/16
    ansible.builtin.lineinfile:
      mode: '400'
      path: "{{ ansible_env.HOME }}/.ssh/config"
      line: "Host 10.137.0.0/16\n    StrictHostKeyChecking no"
      create: yes
      insertafter: EOF



#  root@general /h/w/d/dmoj (master) [1]# sudo ufw allow proto tcp from 10.137.0.0/16 to 10.137.0.0/16 port 2377
#  Rule added
#  root@general /h/w/d/dmoj (master)# sudo ufw allow proto any from 10.137.0.0/16 to 10.137.0.0/16 port 7947
#  Rule added
#  root@general /h/w/d/dmoj (master)# sudo ufw allow proto udp from 10.137.0.0/16 to 10.137.0.0/16 port 4789

# sudo ufw allow from 10.137.0.0/16 to any port nfs





# docker network create --driver overlay --ingress --subnet=10.137.0.0/16 --gateway=10.137.0.5 --opt com.do
#cker.network.driver.mtu=1200 ingress ||||| where 0.5 is general's iIP
