#!/bin/bash

# Function to get all ips of all nodes in the swarm
get_worker_ips() {
  docker node ls --filter role=worker --format "{{.Hostname}}" | \
  xargs docker node inspect --format '{{ .Status.Addr }}'
}
get_manager_ips() {
  docker node ls --filter role=manager --format "{{.Hostname}}" | \
  xargs docker node inspect --format '{{ .Status.Addr }}'
}

# Function to get IP addresses of running replicas for a given service
get_replica_ips() {
  local service_name="$1"

  # Get node names of running tasks
  nodes=$(docker service ps "$service_name" --format '{{.Node}}' | grep running) # TODO: TEST

  for node in $nodes; do
    # Get IP address of the node
  data=$(docker node inspect --format '{{.Description.Hostname}} {{.Status.Addr}}' "$node")
  echo "$data"

  done
}

fetch_inventory() {
  echo "ansible_ssh_common_args=\"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
  echo "[managers]" # todo: if we have multiple managers, we need to place general first
  get_manager_ips
  echo "[workers]"
  get_worker_ips
}
