#!/bin/bash

# Function to get all ips of all nodes in the swarm
get_worker_ips() {
  # check if there are any workers
  local workers
  workers="$(doctl compute droplet list --format PrivateIPv4 --tag-name worker --no-header)"

  if [ -z "$workers" ]; then
    return
  fi
  echo "$workers"
}
get_manager_ips() {
  # check if there are any workers
  local managers
  managers="$(doctl compute droplet list --format PrivateIPv4 --tag-name manager --no-header)"

  if [ -z "$managers" ]; then
    return
  fi
  echo "$managers"
}

# Function to get IP addresses of running replicas for a given service
get_replica_ips() {
  local service_name="$1"

  # Get node names of running tasks
  nodes=$(docker service ps "$service_name" --format '{{.Node}}' | grep running) # TODO: TEST

  for node in $nodes; do
    # Get IP address of the node
    data=$(docker node inspect --format '{{.Description.Hostname}} {{.Status.Addr}}' "$node")
    echo "$data"

  done
}

fetch_inventory() {
  #  echo "ansible_ssh_common_args=\"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
  echo "[managers]" # todo: if we have multiple managers, we need to place general first
  get_manager_ips
  echo "[workers]"
  get_worker_ips
}

update_inventory() {
  fetch_inventory >./inventory.ini
}

get_ip_from_node() {
  local node_name="$1"
  docker node inspect --format '{{ .Status.Addr }}' "$node_name"
}
