#!/bin/bash

cd "$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd -P
)" || exit

# Ensure running on a swarm manager
if [ "$(docker info --format '{{.Swarm.ControlAvailable}}')" != "true" ]; then
  echo "This script must be run on the swarm manager" >&2
  exit 1
fi

. ../dmoj/scripts/utils/notify
. ./swarm_info

function get_judges() {
    local filter_type="$1"
    local container_names=()
    for container_name in $(docker service ls --filter name='judge_'  --format "{{.$filter_type}}"); do
        container_names+=("$container_name")
    done

    echo "${container_names[@]}"
}

function formatted_judges() {
  local judges
  judges="($(get_judges Name))"
  echo "${judges[@]// /, }"  # Replace spaces with commas and spaces
}

function formatted_time() {
  echo "<t:$(date +%s)>"
}

problem_storage_root="$(realpath "$1")"
recent_notifs_file=$(mktemp)


notify "$(formatted_time): Watching ${problem_storage_root}, notifying judges **$(formatted_judges)**"

inotifywait -rm "${problem_storage_root}" -e move,create,delete -q | while read -r line; do
  if [ "$(echo "$line" | cut -d' ' -f3)" != "init.yml" ]; then
    continue
  fi
  problems_raw="$(echo "$line" | cut -d' ' -f1)"
  problems=${problems_raw#"$problem_storage_root"}
  # Extract the top-level directory
  top_dir=$(echo "$problems" | cut -d'/' -f2)

  # Check if this directory has been notified recently
  if ! grep -q "^${top_dir}:" "$recent_notifs_file"; then
    echo "${top_dir}:$(date +%s)" >> "$recent_notifs_file"

    notify "$(formatted_time):  [$problems] on  **$(formatted_judges)**"
    judges="($(get_judges ID))"
    for judge in "${judges[@]}"; do
      curl -4 -s -X POST "http://$judge:9998/update/problems" | sed "s/^/$(date) [$judge]: /"';$a\'
    done
  fi

  # Clean up old entries (older than 10 seconds)
  current_time=$(date +%s)
  temp_file_content=$(awk -v now="$current_time" '{split($0,a,":"); if (now - a[2] <= 10) print $0}' "$recent_notifs_file")
  echo "$temp_file_content" > "$recent_notifs_file"
done